// The app's own commands are declared in the app manifest. Without it, Tauri 2
// allows every registered command to every window; with it, a command can be
// called only where an enabled capability grants its generated permission.
include!("src/command_names.rs");

use std::path::Path;

/// The protocol's canonical schema, the one source of the version and the
/// method list (CLAUDE.md §4). Read here so the native side has no copy.
const SCHEMA: &str = "../../../schemas/protocol/v2.json";

fn main() {
    write_protocol_constants();

    let mut names: Vec<&'static str> = COMMANDS.to_vec();
    if std::env::var_os("CARGO_FEATURE_E2E").is_some() {
        names.push(E2E_COMMAND);
    }
    // tauri-build reads every file under `permissions/`, including one it
    // generated earlier in this checkout for a command this build does not
    // have — the test build's, or one since removed. Such a file would put
    // that command's permissions back in the manifest, so it goes first.
    remove_stale_permissions(&names);
    let names: &'static [&'static str] = Box::leak(names.into_boxed_slice());
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(names)),
    )
    .expect("tauri-build failed");

    // `gen/` is shared by every build configuration of this checkout; the
    // copies in OUT_DIR belong to this one, so its tests read what this
    // build generated and nothing a later test build wrote.
    let out = std::env::var("OUT_DIR").unwrap();
    for file in ["acl-manifests.json", "capabilities.json"] {
        std::fs::copy(Path::new("gen/schemas").join(file), Path::new(&out).join(file))
            .unwrap_or_else(|problem| panic!("copy gen/schemas/{file}: {problem}"));
    }
}

fn remove_stale_permissions(names: &[&str]) {
    let Ok(entries) = std::fs::read_dir("permissions/autogenerated") else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        let stem = path.file_stem().and_then(|stem| stem.to_str()).unwrap_or_default();
        if path.extension().is_some_and(|ext| ext == "toml") && !names.contains(&stem) {
            std::fs::remove_file(&path)
                .unwrap_or_else(|problem| panic!("could not remove {}: {problem}", path.display()));
        }
    }
}

fn write_protocol_constants() {
    println!("cargo:rerun-if-changed={SCHEMA}");
    // Declared, or Cargo would not run this script again when the list changes.
    println!("cargo:rerun-if-changed=src/command_names.rs");
    let text = std::fs::read_to_string(SCHEMA).expect("the protocol schema");
    let schema: serde_json::Value = serde_json::from_str(&text).expect("the schema is JSON");
    let version = schema["x-protocol-version"].as_i64().expect("x-protocol-version");
    let methods: Vec<String> = schema["x-methods"].as_object().expect("x-methods")
        .keys().map(|name| format!("{name:?}")).collect();
    let generated = format!(
        "/// The protocol version, from `schemas/protocol/v2.json`.\n\
         pub const PROTOCOL_VERSION: i64 = {version};\n\
         /// Every protocol method, from `schemas/protocol/v2.json`.\n\
         pub const METHODS: [&str; {}] = [{}];\n",
        methods.len(), methods.join(", "));
    let out = Path::new(&std::env::var("OUT_DIR").unwrap()).join("protocol.rs");
    std::fs::write(out, generated).expect("write protocol.rs");
}
