// The app's own commands are declared in the app manifest. Without it, Tauri 2
// allows every registered command to every window; with it, a command can be
// called only where an enabled capability grants its generated permission.
include!("src/command_names.rs");

fn main() {
    let mut names: Vec<&'static str> = COMMANDS.to_vec();
    if std::env::var_os("CARGO_FEATURE_E2E").is_some() {
        names.push(E2E_COMMAND);
    } else {
        // tauri-build reads every file under `permissions/`, including one a
        // test build generated earlier in this checkout, so a release build
        // removes the test command's file before its manifest is made.
        let stale = format!("permissions/autogenerated/{E2E_COMMAND}.toml");
        match std::fs::remove_file(&stale) {
            Ok(()) => {}
            Err(problem) if problem.kind() == std::io::ErrorKind::NotFound => {}
            Err(problem) => panic!("could not remove {stale}: {problem}"),
        }
    }
    let names: &'static [&'static str] = Box::leak(names.into_boxed_slice());
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(names)),
    )
    .expect("tauri-build failed");
}
