/**
 * Generated by tools/protocol-codegen.py from schemas/protocol/v2.json.
 *
 * Do not edit. Change the schema and regenerate.
 */

export const PROTOCOL_VERSION = 2 as const;

/** Every method a client may call. */
export const METHODS = [
  "client.hello",
  "session.create",
  "session.get",
  "session.snapshot",
  "session.list",
  "session.send",
  "session.cancel",
  "session.set_mode",
  "model.get",
  "model.list",
  "model.set",
  "workspace.get",
  "question.answer",
  "permission.reply",
  "delegate.stop",
  "shutdown",
] as const;
export type Method = (typeof METHODS)[number];

/** Every event the core may emit. */
export const EVENTS = [
  "session.created",
  "session.updated",
  "message.started",
  "message.delta",
  "message.completed",
  "tool.started",
  "tool.output",
  "tool.completed",
  "tool.failed",
  "tasks.updated",
  "delegate.updated",
  "question.requested",
  "question.resolved",
  "permission.requested",
  "permission.resolved",
  "mode.changed",
  "model.changed",
  "notification.created",
] as const;
export type EventName = (typeof EVENTS)[number];

/** Error codes, with the one-line reason each exists. */
export const ERRORS = {
  parse_error: "The line was not JSON, or not an object.",
  invalid_envelope: "JSON, but not one of the four shapes.",
  unsupported_version: "The client asked for a protocol version this core does not speak.",
  not_initialized: "A method other than client.hello arrived before the handshake.",
  already_initialized: "client.hello arrived twice.",
  unknown_method: "No such method.",
  invalid_params: "The method exists; the parameters do not fit it.",
  unknown_session: "No session with that id.",
  unknown_request: "No pending question or permission with that id.",
  not_allowed: "The mode or permission policy refused it.",
  internal_error: "A fault in the core. The message is safe to show; details go to stderr.",
} as const;
export type ErrorCode = keyof typeof ERRORS;

export const CORE_CAPABILITIES = [
  "streaming",
  "questions",
  "permissions",
  "modes",
  "tool_events",
  "tasks",
  "delegates",
] as const;
export const CLIENT_CAPABILITIES = [
  "questions",
  "permissions",
] as const;

export const MODES = [
  "act",
  "plan",
  "ask",
  "chat",
] as const;

/** What the agent is allowed to do. Enforced by the core, not by the client. */
export type Mode = "act" | "plan" | "ask" | "chat";

/** How a message stands. `streaming` means it is still open and more deltas can arrive: a snapshot taken mid-answer must say so, because a client that read an unfinished message as `completed` would stop listening to it. `cancelled` and `failed` are not decoration: a client that cannot tell them from `completed` has to leave a stopped answer looking like one still arriving. */
export type MessageStatus = "streaming" | "completed" | "cancelled" | "failed";

/** Where one tool invocation has got to. */
export type ToolState = "running" | "completed" | "failed";

/** The tier a tool declares, and the reason it is asking. `safe` reads, `write` changes files, `dangerous` runs commands or reaches the network. A client shows it so the person can see what kind of thing they are approving; it is the core's own classification, not a guess the client makes from the tool's name. */
export type RiskLevel = "safe" | "write" | "dangerous";

/** Which sort of blocking interaction is waiting on a person. A question wants information; a permission wants authorization. */
export type InteractionKind = "question" | "permission";

/**
 * A method that takes nothing. Still an object, so a parameter can be added
 * later without a new shape.
 */
export interface Empty {
}

/**
 * Who is on the other end. Reported, never trusted for authorisation.
 */
export interface PeerInfo {
  name: string;
  version: string;
}

export interface HelloParams {
  protocol_version: number;
  client: PeerInfo;
  capabilities?: Array<string>;
}

export interface HelloResult {
  protocol_version: number;
  core: PeerInfo;
  capabilities: Array<string>;
}

/**
 * A session as the core knows it. This is the authoritative shape a client
 * resynchronises against.
 */
export interface Session {
  id: string;
  mode: Mode;
  workspace: string;
  busy: boolean;
  title?: string;
}

export interface SessionRef {
  session_id: string;
}

export interface SessionCreateParams {
  workspace?: string;
  mode?: Mode;
}

export interface SessionResult {
  session: Session;
}

export interface SessionListResult {
  sessions: Array<Session>;
}

/**
 * One message as the core has it. `text` is the whole message, not a delta:
 * a snapshot replaces a projection rather than adding to one.
 */
export interface SnapshotMessage {
  message_id: string;
  turn_id: string;
  role: string;
  text: string;
  reasoning?: string;
  status: MessageStatus;
  started_seq: number;
}

/**
 * One tool invocation as the core has it. `output` is what the core still
 * holds, which is capped; `output_truncated` says so rather than letting a
 * client present a shortened transcript as the whole one.
 */
export interface SnapshotTool {
  call_id: string;
  turn_id: string;
  name: string;
  summary?: string;
  state: ToolState;
  started_seq: number;
  output?: string;
  output_truncated?: boolean;
  error?: string;
  elapsed_ms?: number;
}

/** Where one item of the agent's own plan stands. The vocabulary is the `todo_write` tool's, not the interface's: a client renders these four and invents no others — a frontend-only state such as `queued` would be a claim the core never made. */
export type TaskState = "pending" | "active" | "done" | "blocked";

/**
 * One item of the agent's task list. Tasks carry no id: the list is small,
 * the tool replaces it whole on every update, and an index is not an
 * identity across a replacement. A client that renders the list in order
 * needs nothing more; a future operation on one task would need a real
 * core-owned id, which this deliberately does not fake.
 */
export interface TaskItem {
  text: string;
  state: TaskState;
}

/**
 * The agent's whole task list, as `todo_write` recorded it. Replacement,
 * never addition: a task the new list does not carry is gone, and the order
 * is the order the model wrote. Arrives on the session's sequence like
 * every other event, so a snapshot and a live stream converge on the same
 * list.
 */
export interface TasksUpdated {
  session_id: string;
  tasks: Array<TaskItem>;
}

/** Where one background delegate has got to. `running` and `stopping` are the live states; the other four are terminal and a delegate never comes back from one. `lost` is the honest state of a delegate that was running when the process died: it is reported after a reload rather than pretended to be alive. A state only ever moves forward through this vocabulary — a late announcement cannot walk one backwards. */
export type DelegateState = "running" | "stopping" | "done" | "failed" | "stopped" | "lost";

/**
 * One background delegate, as the core's manager knows it. Every field is a
 * fact the core already keeps: no progress percentage is invented, and
 * `steps`, `tool_calls` and `tokens` are what the worker recorded — zero
 * until it settles, because a running delegate has not reported anything
 * yet. `elapsed` is seconds as of this record; `started_at` is the core's
 * epoch seconds, which lets a client tick a running delegate's clock
 * without asking. `label` is the model's own short name for the work (or
 * the head of its brief) — display text, not a promise.
 */
export interface Delegate {
  id: string;
  label: string;
  state: DelegateState;
  steps: number;
  tool_calls: number;
  tokens: number;
  elapsed: number;
  started_at: number;
  error?: string;
}

/**
 * One background delegate moved. The whole record rides along, so a client
 * replaces what it holds for that id rather than merging fields — and
 * applies the state vocabulary's forward-only rule: an event cannot move a
 * delegate back from `stopping` to `running` or out of a terminal state.
 */
export interface DelegateUpdated {
  session_id: string;
  delegate: Delegate;
}

export interface DelegateStopParams {
  session_id: string;
  delegate_id: string;
}

/**
 * Whether there was a running delegate to stop. `false` is an honest
 * answer, not an error: the delegate may have finished in the instant the
 * request arrived, or never existed. What it actually became arrives as
 * `delegate.updated` — `stopping` when the stop took, then the terminal
 * state the worker settles on. Stopping every delegate at once is
 * deliberately not a protocol operation: one deliberate stop is the surface
 * F5 promises.
 */
export interface DelegateStopResult {
  stopped: boolean;
}

/**
 * Everything a client needs to draw a session it did not watch happen.
 * `revision` is the sequence number this state includes up to: the client
 * drops any event at or below it and applies the rest, which is what makes
 * rebuilding safe while the session is still streaming. Every message and
 * tool carries `started_seq`, the sequence at which it entered the
 * timeline, so the two lists merge into the one order the live stream had
 * rather than being drawn messages-then-tools. `tasks` and `delegates`
 * carry the workbench state the same way: a client that mounts mid-job sees
 * the plan and the delegated work without replaying history, and a client
 * too old to know them ignores them.
 */
export interface SessionSnapshot {
  session: Session;
  revision: number;
  messages: Array<SnapshotMessage>;
  tools: Array<SnapshotTool>;
  tasks?: Array<TaskItem>;
  delegates?: Array<Delegate>;
  question?: QuestionRequest;
  permission?: PermissionRequest;
  interactions?: Array<PendingInteraction>;
}

/**
 * One blocking interaction a snapshot is carrying. Exactly one of
 * `question` or `permission` is present, and `kind` says which, so a client
 * can narrow without inspecting both.
 */
export interface PendingInteraction {
  kind: InteractionKind;
  question?: QuestionRequest;
  permission?: PermissionRequest;
}

export interface SnapshotResult {
  snapshot: SessionSnapshot;
}

export interface SessionSendParams {
  session_id: string;
  text: string;
}

/**
 * The turn was accepted. `turn_id` correlates every message.* and tool.*
 * event it produces. It is a turn and not a message because one turn
 * interleaves several assistant messages with the tools between them, and
 * naming it after the first would make the rest look like repeats of it.
 */
export interface AcceptedResult {
  accepted: boolean;
  turn_id: string;
}

export interface CancelResult {
  cancelled: boolean;
}

export interface SetModeParams {
  session_id: string;
  mode: Mode;
}

/**
 * Never carries a key. `configured` is how a client shows that a provider
 * needs setting up without being told the secret.
 */
export interface ModelResult {
  provider: string;
  model: string;
  configured: boolean;
}

export interface SetModelParams {
  model: string;
  provider?: string;
}

export interface WorkspaceResult {
  path: string;
  name?: string;
}

/**
 * One row a person can pick. `id` is what travels back in `chosen`. `free`
 * marks the write-your-own row, which carries typed text instead of a fixed
 * label and is rendered differently.
 */
export interface QuestionOption {
  id: string;
  label: string;
  description?: string;
  free?: boolean;
}

/**
 * A form the agent is waiting on, as a protocol primitive rather than a
 * numbered list in prose. It carries *several* questions because the agent
 * asks several at once — one round trip rather than four — so a client
 * renders a form, not a prompt.
 */
export interface QuestionRequest {
  id: string;
  session_id: string;
  title: string;
  questions: Array<QuestionField>;
}

export interface QuestionResolved {
  id: string;
  session_id: string;
  answers?: Array<QuestionAnswer>;
  cancelled?: boolean;
}

export interface AnswerParams {
  id: string;
  answers?: Array<QuestionAnswer>;
  cancelled?: boolean;
}

/**
 * A tool call waiting on a person. `detail` is what the core already
 * renders for a human; it is not a command to run. `tool` and `risk` are
 * the context an informed decision needs — which capability is asking, and
 * which tier it belongs to — and are optional so a core that has nothing
 * truthful to say omits them rather than inventing a value.
 */
export interface PermissionRequest {
  id: string;
  session_id: string;
  title: string;
  detail?: string;
  options: Array<string>;
  tool?: string;
  risk?: RiskLevel;
}

export interface PermissionResolved {
  id: string;
  session_id: string;
  choice: string;
}

export interface PermissionReplyParams {
  id: string;
  choice: string;
}

export interface AckResult {
  ok: boolean;
}

export interface SessionEvent {
  session: Session;
}

/**
 * A new assistant message within a turn. Each one has its own `message_id`;
 * `turn_id` is shared by every event the same `session.send` caused.
 */
export interface MessageStarted {
  session_id: string;
  turn_id: string;
  message_id: string;
  role: string;
}

/**
 * One piece of a streamed answer, routed by `message_id` alone. `channel`
 * separates the answer from extended thinking, so a client can show or hide
 * reasoning without guessing from the text.
 */
export interface MessageDelta {
  session_id: string;
  turn_id: string;
  message_id: string;
  text: string;
  channel?: string;
}

/**
 * The message is finished, one way or another. `text` is the whole answer
 * where there is one, so a client that lost a delta is corrected rather
 * than left with a gap. `error` accompanies `status: failed` and is written
 * to be shown.
 */
export interface MessageCompleted {
  session_id: string;
  turn_id: string;
  message_id: string;
  text?: string;
  status: MessageStatus;
  error?: string;
}

export interface ToolStarted {
  session_id: string;
  turn_id: string;
  call_id: string;
  name: string;
  summary?: string;
}

/**
 * Incremental output from a running tool, such as a shell command's lines
 * as they arrive. `call_id` is required: the core binds the running call to
 * the thread producing the output, so output from tools running in parallel
 * cannot be attributed to whichever started last.
 */
export interface ToolOutput {
  session_id: string;
  turn_id: string;
  call_id: string;
  text: string;
}

export interface ToolCompleted {
  session_id: string;
  turn_id: string;
  call_id: string;
  name?: string;
  summary?: string;
  elapsed_ms?: number;
}

export interface ToolFailed {
  session_id: string;
  turn_id: string;
  call_id: string;
  name?: string;
  error: string;
}

export interface ModeChanged {
  session_id: string;
  mode: Mode;
}

/**
 * Something worth saying that is not part of an answer. `level` is
 * advisory; a client may style it.
 */
export interface Notification {
  session_id?: string;
  level: "info" | "warning" | "error";
  text: string;
}

export interface Error_ {
  code: string;
  message: string;
  data?: Record<string, unknown>;
}

/**
 * One question within a form. `header` is its stable name and is what an
 * answer is matched on — not the position, which would silently reattach
 * every answer if a question were reordered.
 */
export interface QuestionField {
  header: string;
  prompt: string;
  options: Array<QuestionOption>;
  multiple: boolean;
}

/**
 * What came back for one question. `chosen` holds option ids; `written`
 * holds what was typed into the free row.
 */
export interface QuestionAnswer {
  header: string;
  chosen: Array<string>;
  written?: string;
}

/**
 * A model chooser's source of truth. `models` is the provider's own list
 * with the configured model guaranteed present; it is never empty when a
 * model is configured.
 */
export interface ModelListResult {
  provider: string;
  model: string;
  configured?: boolean;
  models: Array<string>;
}

/**
 * One JSON object per line, UTF-8, no embedded newlines. Four shapes,
 * distinguished by `type`. An event also carries `seq`: the session's own
 * monotonic counter, starting at 1, which is what makes a snapshot and a
 * live stream reconcilable rather than merely usually consistent.
 */
export interface RequestEnvelope {
  version: typeof PROTOCOL_VERSION;
  type: "request";
  id: string;
  method: Method;
  params: Record<string, unknown>;
}

export interface ResponseEnvelope {
  version: typeof PROTOCOL_VERSION;
  type: "response";
  id: string;
  result: Record<string, unknown>;
}

export interface ErrorEnvelope {
  version: typeof PROTOCOL_VERSION;
  type: "error";
  id: string | null;
  error: Error_;
}

export interface EventEnvelope {
  version: typeof PROTOCOL_VERSION;
  type: "event";
  event: EventName;
  /** This session's monotonic counter. See `x-envelope`. */
  seq: number;
  params: Record<string, unknown>;
}

export type Envelope =
  | RequestEnvelope
  | ResponseEnvelope
  | ErrorEnvelope
  | EventEnvelope;
