/**
 * Generated by tools/protocol-codegen.py from schemas/protocol/v1.json.
 *
 * Do not edit. Change the schema and regenerate.
 */

export const PROTOCOL_VERSION = 1 as const;

/** Every method a client may call. */
export const METHODS = [
  "client.hello",
  "session.create",
  "session.get",
  "session.list",
  "session.send",
  "session.cancel",
  "session.set_mode",
  "model.get",
  "model.set",
  "workspace.get",
  "question.answer",
  "permission.reply",
  "shutdown",
] as const;
export type Method = (typeof METHODS)[number];

/** Every event the core may emit. */
export const EVENTS = [
  "session.created",
  "session.updated",
  "message.started",
  "message.delta",
  "message.completed",
  "tool.started",
  "tool.output",
  "tool.completed",
  "tool.failed",
  "question.requested",
  "question.resolved",
  "permission.requested",
  "permission.resolved",
  "mode.changed",
  "model.changed",
  "notification.created",
] as const;
export type EventName = (typeof EVENTS)[number];

/** Error codes, with the one-line reason each exists. */
export const ERRORS = {
  parse_error: "The line was not JSON, or not an object.",
  invalid_envelope: "JSON, but not one of the four shapes.",
  unsupported_version: "The client asked for a protocol version this core does not speak.",
  not_initialized: "A method other than client.hello arrived before the handshake.",
  already_initialized: "client.hello arrived twice.",
  unknown_method: "No such method.",
  invalid_params: "The method exists; the parameters do not fit it.",
  unknown_session: "No session with that id.",
  unknown_request: "No pending question or permission with that id.",
  not_allowed: "The mode or permission policy refused it.",
  internal_error: "A fault in the core. The message is safe to show; details go to stderr.",
} as const;
export type ErrorCode = keyof typeof ERRORS;

export const CORE_CAPABILITIES = [
  "streaming",
  "questions",
  "permissions",
  "modes",
  "tool_events",
] as const;
export const CLIENT_CAPABILITIES = [
  "questions",
  "permissions",
] as const;

export const MODES = [
  "act",
  "plan",
  "ask",
  "chat",
] as const;

/** What the agent is allowed to do. Enforced by the core, not by the client. */
export type Mode = "act" | "plan" | "ask" | "chat";

/**
 * A method that takes nothing. Still an object, so a parameter can be added
 * later without a new shape.
 */
export interface Empty {
}

/**
 * Who is on the other end. Reported, never trusted for authorisation.
 */
export interface PeerInfo {
  name: string;
  version: string;
}

export interface HelloParams {
  protocol_version: number;
  client: PeerInfo;
  capabilities?: Array<string>;
}

export interface HelloResult {
  protocol_version: number;
  core: PeerInfo;
  capabilities: Array<string>;
}

/**
 * A session as the core knows it. This is the authoritative shape a client
 * resynchronises against.
 */
export interface Session {
  id: string;
  mode: Mode;
  workspace: string;
  busy: boolean;
  title?: string;
}

export interface SessionRef {
  session_id: string;
}

export interface SessionCreateParams {
  workspace?: string;
  mode?: Mode;
}

export interface SessionResult {
  session: Session;
}

export interface SessionListResult {
  sessions: Array<Session>;
}

export interface SessionSendParams {
  session_id: string;
  text: string;
}

/**
 * The turn was accepted. `message_id` correlates every message.* event that
 * follows.
 */
export interface AcceptedResult {
  accepted: boolean;
  message_id: string;
}

export interface CancelResult {
  cancelled: boolean;
}

export interface SetModeParams {
  session_id: string;
  mode: Mode;
}

/**
 * Never carries a key. `configured` is how a client shows that a provider
 * needs setting up without being told the secret.
 */
export interface ModelResult {
  provider: string;
  model: string;
  configured: boolean;
}

export interface SetModelParams {
  model: string;
  provider?: string;
}

export interface WorkspaceResult {
  path: string;
  name?: string;
}

/**
 * One row a person can pick. `id` is what travels back in `chosen`. `free`
 * marks the write-your-own row, which carries typed text instead of a fixed
 * label and is rendered differently.
 */
export interface QuestionOption {
  id: string;
  label: string;
  description?: string;
  free?: boolean;
}

/**
 * A form the agent is waiting on, as a protocol primitive rather than a
 * numbered list in prose. It carries *several* questions because the agent
 * asks several at once — one round trip rather than four — so a client
 * renders a form, not a prompt.
 */
export interface QuestionRequest {
  id: string;
  session_id: string;
  title: string;
  questions: Array<QuestionField>;
}

export interface QuestionResolved {
  id: string;
  session_id: string;
  answers?: Array<QuestionAnswer>;
  cancelled?: boolean;
}

export interface AnswerParams {
  id: string;
  answers?: Array<QuestionAnswer>;
  cancelled?: boolean;
}

/**
 * A tool call waiting on a person. `detail` is what the core already
 * renders for a human; it is not a command to run.
 */
export interface PermissionRequest {
  id: string;
  session_id: string;
  title: string;
  detail?: string;
  options: Array<string>;
}

export interface PermissionResolved {
  id: string;
  session_id: string;
  choice: string;
}

export interface PermissionReplyParams {
  id: string;
  choice: string;
}

export interface AckResult {
  ok: boolean;
}

export interface SessionEvent {
  session: Session;
}

export interface MessageStarted {
  session_id: string;
  message_id: string;
  role: string;
}

/**
 * One piece of a streamed answer. `channel` separates the answer from
 * extended thinking, so a client can show or hide reasoning without
 * guessing from the text.
 */
export interface MessageDelta {
  session_id: string;
  message_id: string;
  text: string;
  channel?: string;
}

export interface MessageCompleted {
  session_id: string;
  message_id: string;
  text?: string;
  cancelled?: boolean;
}

export interface ToolStarted {
  session_id: string;
  call_id: string;
  name: string;
  summary?: string;
}

/**
 * Incremental output from a running tool, such as a shell command's lines
 * as they arrive. `call_id` is optional because the core does not tag
 * streamed output with the call it came from, and two tools can run at once
 * — attributing it to the most recently started call would be right most of
 * the time and quietly wrong under parallel execution. A client shows it
 * against the session unless a call is named.
 */
export interface ToolOutput {
  session_id: string;
  call_id?: string;
  text: string;
}

export interface ToolCompleted {
  session_id: string;
  call_id: string;
  name?: string;
  summary?: string;
  elapsed_ms?: number;
}

export interface ToolFailed {
  session_id: string;
  call_id: string;
  name?: string;
  error: string;
}

export interface ModeChanged {
  session_id: string;
  mode: Mode;
}

/**
 * Something worth saying that is not part of an answer. `level` is
 * advisory; a client may style it.
 */
export interface Notification {
  session_id?: string;
  level: "info" | "warning" | "error";
  text: string;
}

export interface Error_ {
  code: string;
  message: string;
  data?: Record<string, unknown>;
}

/**
 * One question within a form. `header` is its stable name and is what an
 * answer is matched on — not the position, which would silently reattach
 * every answer if a question were reordered.
 */
export interface QuestionField {
  header: string;
  prompt: string;
  options: Array<QuestionOption>;
  multiple: boolean;
}

/**
 * What came back for one question. `chosen` holds option ids; `written`
 * holds what was typed into the free row.
 */
export interface QuestionAnswer {
  header: string;
  chosen: Array<string>;
  written?: string;
}

/**
 * One JSON object per line, UTF-8, no embedded newlines. Four shapes,
 * distinguished by `type`.
 */
export interface RequestEnvelope {
  version: typeof PROTOCOL_VERSION;
  type: "request";
  id: string;
  method: Method;
  params: Record<string, unknown>;
}

export interface ResponseEnvelope {
  version: typeof PROTOCOL_VERSION;
  type: "response";
  id: string;
  result: Record<string, unknown>;
}

export interface ErrorEnvelope {
  version: typeof PROTOCOL_VERSION;
  type: "error";
  id: string | null;
  error: Error_;
}

export interface EventEnvelope {
  version: typeof PROTOCOL_VERSION;
  type: "event";
  event: EventName;
  params: Record<string, unknown>;
}

export type Envelope =
  | RequestEnvelope
  | ResponseEnvelope
  | ErrorEnvelope
  | EventEnvelope;
