/**
 * Write the `Link:` header that turns Cloudflare's Early Hints on for this page.
 *
 * Early Hints is enabled on the zone and does nothing, because it works by
 * replaying `Link: rel=preload` headers it has seen on a response — and this
 * site sends none. The preloads it does have are `<link>` tags in the document,
 * which a browser cannot act on until the document has arrived. A header can be
 * sent as a 103 before the HTML exists, so the stylesheet and the fonts are
 * already in flight while the origin is still assembling the page.
 *
 * The filenames are content-hashed and change on every build, so this is
 * generated from what was actually built rather than written by hand — a
 * hand-written preload for a file that no longer exists is a wasted round trip
 * on every visit, and nothing anywhere would report it.
 *
 * Run after `next build`, before deploying.
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const out = path.join(process.cwd(), 'out');
const html = await readFile(path.join(out, 'index.html'), 'utf8');

/** Only what the first screen genuinely needs. */
const wanted = [];

const stylesheet = html.match(/href="(\/_next\/static\/css\/[^"]+\.css)"/);
if (stylesheet) wanted.push({ href: stylesheet[1], as: 'style' });

// The fonts the stylesheet asks for. Preloading every face would push four
// files a visitor may never see; the two the hero is set in are the ones that
// decide when the first sentence stops being invisible.
const css = stylesheet
  ? await readFile(path.join(out, stylesheet[1]), 'utf8')
  : '';
const faces = [...css.matchAll(/url\((\/_next\/static\/media\/[^)]+\.woff2)\)/g)]
  .map((m) => m[1]);
for (const href of [...new Set(faces)].slice(0, 2)) {
  wanted.push({ href, as: 'font', extra: 'type="font/woff2"; crossorigin' });
}

// The hero illustration. It is fetched by script rather than by the parser, so
// without this it cannot start until the JavaScript has run.
wanted.push({ href: '/earth.svg', as: 'fetch', extra: 'crossorigin' });

const value = wanted
  .map(({ href, as, extra }) =>
    `<${href}>; rel=preload; as=${as}${extra ? `; ${extra}` : ''}`)
  .join(', ');

const headers = path.join(out, '_headers');
let existing = await readFile(headers, 'utf8').catch(() => '');

// Replace a block from a previous run rather than stacking them up.
const marker = '# --- generated by tools/early-hints.mjs ---';
const end = '# --- end generated ---';
const start = existing.indexOf(marker);
if (start !== -1) {
  const stop = existing.indexOf(end, start);
  existing = existing.slice(0, start) + existing.slice(stop + end.length);
}

const block = [
  '',
  marker,
  '# Filenames are content-hashed, so this is written from the build rather',
  '# than by hand. Cloudflare replays these as a 103 before the HTML exists.',
  '/',
  `  Link: ${value}`,
  end,
  '',
].join('\n');

await writeFile(headers, existing.trimEnd() + '\n' + block, 'utf8');

console.log(`  wrote ${wanted.length} preload hints into out/_headers`);
for (const { href, as } of wanted) console.log(`    ${as.padEnd(6)} ${href}`);
