#!/usr/bin/env python3
"""Turn `schemas/protocol/v1.json` into Python and TypeScript.

Two languages have to agree about a wire format, and the usual way that fails
is quiet: somebody adds a field on one side, the other side keeps parsing, and
the disagreement is discovered by a user. So neither side is written by hand.
This reads the schema and writes both, and `tests/test_protocol_schema.py`
regenerates them and fails if either differs from what is committed.

That is the whole mechanism. It is deliberately small — no plugin system, no
template engine, no dependency — because a generator complex enough to need
its own tests is a second thing that can be wrong.

    python tools/protocol-codegen.py            # write the files
    python tools/protocol-codegen.py --check    # exit 1 if they would change

Only the subset of JSON Schema the protocol actually uses is understood:
objects with named properties, `$ref` into `$defs`, arrays, strings with an
optional `enum`, integers and booleans. Anything else raises rather than
guessing, so an unsupported construct is a build failure and never a silently
wrong type.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schemas" / "protocol" / "v1.json"
PYTHON_OUT = ROOT / "src" / "comodor" / "protocol" / "_generated.py"
TS_OUT = ROOT / "packages" / "protocol" / "src" / "generated.ts"

BANNER = "Generated by tools/protocol-codegen.py from schemas/protocol/v1.json."
DO_NOT_EDIT = "Do not edit. Change the schema and regenerate."


class Unsupported(Exception):
    """A schema construct this generator will not guess at."""


# --------------------------------------------------------------------------- #
# reading the schema
# --------------------------------------------------------------------------- #

def load() -> dict[str, Any]:
    with SCHEMA.open(encoding="utf-8") as handle:
        return json.load(handle)


def ref_name(node: dict[str, Any]) -> str:
    target = node["$ref"]
    prefix = "#/$defs/"
    if not target.startswith(prefix):
        raise Unsupported(f"only #/$defs/ references are supported, got {target!r}")
    return target[len(prefix):]


def python_type(node: dict[str, Any], defs: dict[str, Any]) -> str:
    if "$ref" in node:
        target = ref_name(node)
        # Only object shapes become Python classes. A string enum is a `str`
        # on the wire and has no generated type to name, so referring to it by
        # name would produce an annotation for something that does not exist.
        if defs.get(target, {}).get("type") != "object":
            return python_type(defs[target], defs)
        return target
    kind = node.get("type")
    if kind == "string":
        return "str"
    if kind == "integer":
        return "int"
    if kind == "number":
        return "float"
    if kind == "boolean":
        return "bool"
    if kind == "array":
        return f"list[{python_type(node['items'], defs)}]"
    if kind == "object":
        return "dict[str, Any]"
    raise Unsupported(f"no Python type for {node!r}")


def ts_type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return ref_name(node)
    kind = node.get("type")
    if kind == "string":
        options = node.get("enum")
        if options:
            return " | ".join(json.dumps(value) for value in options)
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        return f"Array<{ts_type(node['items'])}>"
    if kind == "object":
        return "Record<string, unknown>"
    raise Unsupported(f"no TypeScript type for {node!r}")


def wrap(text: str, width: int, indent: str) -> list[str]:
    """Soft-wrap a description into comment lines."""
    words = text.split()
    lines: list[str] = []
    current = indent
    for word in words:
        # `current == indent` means nothing has been placed on this line yet,
        # so the word goes *after* the indent rather than replacing it. Getting
        # this wrong loses the comment marker on the first line only, which is
        # exactly the kind of thing that reads as fine until it is compiled.
        candidate = f"{indent}{word}" if current == indent else f"{current} {word}"
        if len(candidate) > width and current != indent:
            lines.append(current)
            current = f"{indent}{word}"
        else:
            current = candidate
    if current != indent:
        lines.append(current)
    return lines


# --------------------------------------------------------------------------- #
# Python
# --------------------------------------------------------------------------- #

def python_source(schema: dict[str, Any]) -> str:
    defs = schema["$defs"]
    out: list[str] = []
    add = out.append

    add('"""' + BANNER)
    add("")
    add(DO_NOT_EDIT)
    add('"""')
    add("")
    add("from __future__ import annotations")
    add("")
    add("from typing import Any, TypedDict")
    add("")
    add(f'PROTOCOL_VERSION = {schema["x-protocol-version"]}')
    add("")

    # Envelope field lists, so the framing code and the tests read the same
    # definition rather than each having an opinion about it.
    envelope = schema["x-envelope"]
    add("#: The keys each envelope shape carries, in the order the schema lists them.")
    add("ENVELOPE_FIELDS: dict[str, tuple[str, ...]] = {")
    for shape in ("request", "response", "error", "event"):
        fields = ", ".join(f'"{name}"' for name in envelope[shape])
        add(f'    "{shape}": ({fields},),')
    add("}")
    add("")

    methods = schema["x-methods"]
    add("#: Every method a client may call, and the shapes on either side of it.")
    add("METHOD_SHAPES: dict[str, tuple[str, str]] = {")
    for name, spec in methods.items():
        add(f'    "{name}": ("{spec["params"]}", "{spec["result"]}"),')
    add("}")
    add("")
    add("METHODS: frozenset[str] = frozenset(METHOD_SHAPES)")
    add("")

    events = schema["x-events"]
    add("#: Every event the core may emit, and the shape of its params.")
    add("EVENT_SHAPES: dict[str, str] = {")
    for name, shape in events.items():
        add(f'    "{name}": "{shape}",')
    add("}")
    add("")
    add("EVENTS: frozenset[str] = frozenset(EVENT_SHAPES)")
    add("")

    add("#: Error codes, with the one-line reason each exists.")
    add("ERRORS: dict[str, str] = {")
    for code, why in schema["x-errors"].items():
        add(f'    "{code}": {json.dumps(why)},')
    add("}")
    add("")
    for code in schema["x-errors"]:
        add(f'{code.upper()} = "{code}"')
    add("")

    capabilities = schema["x-capabilities"]
    # One name per line: the joined form is one edit away from exceeding the
    # line limit, and a generated file that fails lint blocks everyone.
    for constant, names in (("CORE_CAPABILITIES", capabilities["core"]),
                            ("CLIENT_CAPABILITIES", capabilities["client"])):
        add(f"{constant}: tuple[str, ...] = (")
        for name in names:
            add(f'    "{name}",')
        add(")")
    add("")

    mode_values = ", ".join(f'"{value}"' for value in defs["Mode"]["enum"])
    add(f"MODES: tuple[str, ...] = ({mode_values},)")
    add("")
    add("")

    # The shape table drives validation. Keeping it as data rather than as
    # generated `if` statements means the validator is one small function that
    # is read once, instead of one branch per field that nobody reads at all.
    add("#: field -> (type name, required) for every named shape.")
    add("SHAPES: dict[str, dict[str, tuple[str, bool]]] = {")
    for name, node in defs.items():
        if node.get("type") != "object":
            continue
        required = set(node.get("required", []))
        add(f'    "{name}": {{')
        for field, spec in node.get("properties", {}).items():
            add(f'        "{field}": ({json.dumps(_shape_kind(spec))}, '
                f'{field in required}),')
        add("    },")
    add("}")
    add("")
    add("")

    for name, node in defs.items():
        if node.get("type") != "object":
            continue
        _python_typed_dict(add, name, node, defs)

    return "\n".join(out).rstrip() + "\n"


def _shape_kind(node: dict[str, Any]) -> str:
    """A one-word type name the runtime validator understands."""
    if "$ref" in node:
        target = ref_name(node)
        # An enum behind a reference is still a string on the wire.
        return "str" if target == "Mode" else target
    kind = node.get("type")
    return {"string": "str", "integer": "int", "number": "float",
            "boolean": "bool", "array": "list", "object": "dict"}[kind]


def _python_typed_dict(add, name: str, node: dict[str, Any],
                       defs: dict[str, Any]) -> None:
    required = [f for f in node.get("properties", {}) if f in set(node.get("required", []))]
    optional = [f for f in node.get("properties", {}) if f not in set(node.get("required", []))]
    properties = node.get("properties", {})
    description = node.get("description")

    # Two classes when there are optional keys, because `TypedDict` has one
    # `total` for the whole class and Python 3.9 has no `NotRequired`.
    base = f"_{name}Required" if optional else name

    add(f"class {base}(TypedDict):")
    # The description goes on whichever class a reader will look at: the one
    # named after the shape. When there are optional fields that is the
    # subclass, so the base is left bare rather than documented twice.
    documented = bool(description) and not optional
    if documented:
        _docstring(add, description)
    if not required and not documented:
        add("    pass")
    for field in required:
        add(f"    {field}: {python_type(properties[field], defs)}")
    add("")
    add("")

    if optional:
        add(f"class {name}({base}, total=False):")
        if description:
            _docstring(add, description)
        for field in optional:
            add(f"    {field}: {python_type(properties[field], defs)}")
        add("")
        add("")


def _docstring(add, description: str) -> None:
    lines = wrap(description, 74, "    ")
    if len(lines) == 1:
        add(f'    """{lines[0].strip()}"""')
    else:
        add('    """' + lines[0].strip())
        for line in lines[1:]:
            add(line)
        add('    """')
    add("")


# --------------------------------------------------------------------------- #
# TypeScript
# --------------------------------------------------------------------------- #

def ts_source(schema: dict[str, Any]) -> str:
    defs = schema["$defs"]
    out: list[str] = []
    add = out.append

    add("/**")
    add(f" * {BANNER}")
    add(" *")
    add(f" * {DO_NOT_EDIT}")
    add(" */")
    add("")
    add(f"export const PROTOCOL_VERSION = {schema['x-protocol-version']} as const;")
    add("")

    methods = schema["x-methods"]
    add("/** Every method a client may call. */")
    add("export const METHODS = [")
    for name in methods:
        add(f'  {json.dumps(name)},')
    add("] as const;")
    add("export type Method = (typeof METHODS)[number];")
    add("")

    events = schema["x-events"]
    add("/** Every event the core may emit. */")
    add("export const EVENTS = [")
    for name in events:
        add(f'  {json.dumps(name)},')
    add("] as const;")
    add("export type EventName = (typeof EVENTS)[number];")
    add("")

    add("/** Error codes, with the one-line reason each exists. */")
    add("export const ERRORS = {")
    for code, why in schema["x-errors"].items():
        add(f'  {code}: {json.dumps(why)},')
    add("} as const;")
    add("export type ErrorCode = keyof typeof ERRORS;")
    add("")

    capabilities = schema["x-capabilities"]
    add("export const CORE_CAPABILITIES = [")
    for name in capabilities["core"]:
        add(f"  {json.dumps(name)},")
    add("] as const;")
    add("export const CLIENT_CAPABILITIES = [")
    for name in capabilities["client"]:
        add(f"  {json.dumps(name)},")
    add("] as const;")
    add("")

    add("export const MODES = [")
    for value in defs["Mode"]["enum"]:
        add(f"  {json.dumps(value)},")
    add("] as const;")
    add("")

    # Named types, in schema order.
    for name, node in defs.items():
        if node.get("type") == "string" and "enum" in node:
            union = " | ".join(json.dumps(value) for value in node["enum"])
            if node.get("description"):
                add(f"/** {node['description']} */")
            add(f"export type {name} = {union};")
            add("")
            continue
        if node.get("type") != "object":
            raise Unsupported(f"{name}: only objects and string enums are generated")
        if node.get("description"):
            add("/**")
            for line in wrap(node["description"], 76, " * "):
                add(line)
            add(" */")
        add(f"export interface {name} {{")
        required = set(node.get("required", []))
        for field, spec in node.get("properties", {}).items():
            mark = "" if field in required else "?"
            add(f"  {field}{mark}: {ts_type(spec)};")
        add("}")
        add("")

    # The four envelopes, which are the only place `type` is a discriminator.
    envelope = schema["x-envelope"]
    add("/**")
    for line in wrap(envelope["description"], 76, " * "):
        add(line)
    add(" */")
    add("export interface RequestEnvelope {")
    add("  version: typeof PROTOCOL_VERSION;")
    add('  type: "request";')
    add("  id: string;")
    add("  method: Method;")
    add("  params: Record<string, unknown>;")
    add("}")
    add("")
    add("export interface ResponseEnvelope {")
    add("  version: typeof PROTOCOL_VERSION;")
    add('  type: "response";')
    add("  id: string;")
    add("  result: Record<string, unknown>;")
    add("}")
    add("")
    add("export interface ErrorEnvelope {")
    add("  version: typeof PROTOCOL_VERSION;")
    add('  type: "error";')
    add("  id: string | null;")
    add("  error: Error_;")
    add("}")
    add("")
    add("export interface EventEnvelope {")
    add("  version: typeof PROTOCOL_VERSION;")
    add('  type: "event";')
    add("  event: EventName;")
    add("  params: Record<string, unknown>;")
    add("}")
    add("")
    add("export type Envelope =")
    add("  | RequestEnvelope")
    add("  | ResponseEnvelope")
    add("  | ErrorEnvelope")
    add("  | EventEnvelope;")
    add("")

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- #

def render() -> dict[Path, str]:
    schema = load()
    python = python_source(schema)
    typescript = ts_source(schema).replace("export interface Error {",
                                           "export interface Error_ {")
    return {PYTHON_OUT: python, TS_OUT: typescript}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if a generated file is out of date")
    args = parser.parse_args(argv)

    stale: list[Path] = []
    for path, text in render().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if args.check:
            stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        # Newline pinned so a checkout on Windows and one on Linux generate the
        # same bytes; otherwise --check fails for everyone on one platform.
        with path.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print(f"wrote {path.relative_to(ROOT)}")

    if stale:
        for path in stale:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
        print("run: python tools/protocol-codegen.py", file=sys.stderr)
        return 1
    if args.check:
        print("protocol types are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
