"""Generated by tools/protocol-codegen.py from schemas/protocol/v1.json.

Do not edit. Change the schema and regenerate.
"""

from __future__ import annotations

from typing import Any, TypedDict

PROTOCOL_VERSION = 1

#: The keys each envelope shape carries, in the order the schema lists them.
ENVELOPE_FIELDS: dict[str, tuple[str, ...]] = {
    "request": ("version", "type", "id", "method", "params",),
    "response": ("version", "type", "id", "result",),
    "error": ("version", "type", "id", "error",),
    "event": ("version", "type", "event", "params",),
}

#: Every method a client may call, and the shapes on either side of it.
METHOD_SHAPES: dict[str, tuple[str, str]] = {
    "client.hello": ("HelloParams", "HelloResult"),
    "session.create": ("SessionCreateParams", "SessionResult"),
    "session.get": ("SessionRef", "SessionResult"),
    "session.list": ("Empty", "SessionListResult"),
    "session.send": ("SessionSendParams", "AcceptedResult"),
    "session.cancel": ("SessionRef", "CancelResult"),
    "session.set_mode": ("SetModeParams", "SessionResult"),
    "model.get": ("Empty", "ModelResult"),
    "model.set": ("SetModelParams", "ModelResult"),
    "workspace.get": ("Empty", "WorkspaceResult"),
    "question.answer": ("AnswerParams", "AckResult"),
    "permission.reply": ("PermissionReplyParams", "AckResult"),
    "shutdown": ("Empty", "AckResult"),
}

METHODS: frozenset[str] = frozenset(METHOD_SHAPES)

#: Every event the core may emit, and the shape of its params.
EVENT_SHAPES: dict[str, str] = {
    "session.created": "SessionEvent",
    "session.updated": "SessionEvent",
    "message.started": "MessageStarted",
    "message.delta": "MessageDelta",
    "message.completed": "MessageCompleted",
    "tool.started": "ToolStarted",
    "tool.output": "ToolOutput",
    "tool.completed": "ToolCompleted",
    "tool.failed": "ToolFailed",
    "question.requested": "QuestionRequest",
    "question.resolved": "QuestionResolved",
    "permission.requested": "PermissionRequest",
    "permission.resolved": "PermissionResolved",
    "mode.changed": "ModeChanged",
    "model.changed": "ModelResult",
    "notification.created": "Notification",
}

EVENTS: frozenset[str] = frozenset(EVENT_SHAPES)

#: Error codes, with the one-line reason each exists.
ERRORS: dict[str, str] = {
    "parse_error": "The line was not JSON, or not an object.",
    "invalid_envelope": "JSON, but not one of the four shapes.",
    "unsupported_version": "The client asked for a protocol version this core does not speak.",
    "not_initialized": "A method other than client.hello arrived before the handshake.",
    "already_initialized": "client.hello arrived twice.",
    "unknown_method": "No such method.",
    "invalid_params": "The method exists; the parameters do not fit it.",
    "unknown_session": "No session with that id.",
    "unknown_request": "No pending question or permission with that id.",
    "not_allowed": "The mode or permission policy refused it.",
    "internal_error": "A fault in the core. The message is safe to show; details go to stderr.",
}

PARSE_ERROR = "parse_error"
INVALID_ENVELOPE = "invalid_envelope"
UNSUPPORTED_VERSION = "unsupported_version"
NOT_INITIALIZED = "not_initialized"
ALREADY_INITIALIZED = "already_initialized"
UNKNOWN_METHOD = "unknown_method"
INVALID_PARAMS = "invalid_params"
UNKNOWN_SESSION = "unknown_session"
UNKNOWN_REQUEST = "unknown_request"
NOT_ALLOWED = "not_allowed"
INTERNAL_ERROR = "internal_error"

CORE_CAPABILITIES: tuple[str, ...] = (
    "streaming",
    "questions",
    "permissions",
    "modes",
    "tool_events",
)
CLIENT_CAPABILITIES: tuple[str, ...] = (
    "questions",
    "permissions",
)

MODES: tuple[str, ...] = ("act", "plan", "ask", "chat",)


#: field -> (type name, required) for every named shape.
SHAPES: dict[str, dict[str, tuple[str, bool]]] = {
    "Empty": {
    },
    "PeerInfo": {
        "name": ("str", True),
        "version": ("str", True),
    },
    "HelloParams": {
        "protocol_version": ("int", True),
        "client": ("PeerInfo", True),
        "capabilities": ("list", False),
    },
    "HelloResult": {
        "protocol_version": ("int", True),
        "core": ("PeerInfo", True),
        "capabilities": ("list", True),
    },
    "Session": {
        "id": ("str", True),
        "mode": ("str", True),
        "workspace": ("str", True),
        "busy": ("bool", True),
        "title": ("str", False),
    },
    "SessionRef": {
        "session_id": ("str", True),
    },
    "SessionCreateParams": {
        "workspace": ("str", False),
        "mode": ("str", False),
    },
    "SessionResult": {
        "session": ("Session", True),
    },
    "SessionListResult": {
        "sessions": ("list", True),
    },
    "SessionSendParams": {
        "session_id": ("str", True),
        "text": ("str", True),
    },
    "AcceptedResult": {
        "accepted": ("bool", True),
        "message_id": ("str", True),
    },
    "CancelResult": {
        "cancelled": ("bool", True),
    },
    "SetModeParams": {
        "session_id": ("str", True),
        "mode": ("str", True),
    },
    "ModelResult": {
        "provider": ("str", True),
        "model": ("str", True),
        "configured": ("bool", True),
    },
    "SetModelParams": {
        "model": ("str", True),
        "provider": ("str", False),
    },
    "WorkspaceResult": {
        "path": ("str", True),
        "name": ("str", False),
    },
    "QuestionOption": {
        "id": ("str", True),
        "label": ("str", True),
        "description": ("str", False),
        "free": ("bool", False),
    },
    "QuestionRequest": {
        "id": ("str", True),
        "session_id": ("str", True),
        "title": ("str", True),
        "questions": ("list", True),
    },
    "QuestionResolved": {
        "id": ("str", True),
        "session_id": ("str", True),
        "answers": ("list", False),
        "cancelled": ("bool", False),
    },
    "AnswerParams": {
        "id": ("str", True),
        "answers": ("list", False),
        "cancelled": ("bool", False),
    },
    "PermissionRequest": {
        "id": ("str", True),
        "session_id": ("str", True),
        "title": ("str", True),
        "detail": ("str", False),
        "options": ("list", True),
    },
    "PermissionResolved": {
        "id": ("str", True),
        "session_id": ("str", True),
        "choice": ("str", True),
    },
    "PermissionReplyParams": {
        "id": ("str", True),
        "choice": ("str", True),
    },
    "AckResult": {
        "ok": ("bool", True),
    },
    "SessionEvent": {
        "session": ("Session", True),
    },
    "MessageStarted": {
        "session_id": ("str", True),
        "message_id": ("str", True),
        "role": ("str", True),
    },
    "MessageDelta": {
        "session_id": ("str", True),
        "message_id": ("str", True),
        "text": ("str", True),
        "channel": ("str", False),
    },
    "MessageCompleted": {
        "session_id": ("str", True),
        "message_id": ("str", True),
        "text": ("str", False),
        "cancelled": ("bool", False),
    },
    "ToolStarted": {
        "session_id": ("str", True),
        "call_id": ("str", True),
        "name": ("str", True),
        "summary": ("str", False),
    },
    "ToolOutput": {
        "session_id": ("str", True),
        "call_id": ("str", False),
        "text": ("str", True),
    },
    "ToolCompleted": {
        "session_id": ("str", True),
        "call_id": ("str", True),
        "name": ("str", False),
        "summary": ("str", False),
        "elapsed_ms": ("int", False),
    },
    "ToolFailed": {
        "session_id": ("str", True),
        "call_id": ("str", True),
        "name": ("str", False),
        "error": ("str", True),
    },
    "ModeChanged": {
        "session_id": ("str", True),
        "mode": ("str", True),
    },
    "Notification": {
        "session_id": ("str", False),
        "level": ("str", True),
        "text": ("str", True),
    },
    "Error": {
        "code": ("str", True),
        "message": ("str", True),
        "data": ("dict", False),
    },
    "QuestionField": {
        "header": ("str", True),
        "prompt": ("str", True),
        "options": ("list", True),
        "multiple": ("bool", True),
    },
    "QuestionAnswer": {
        "header": ("str", True),
        "chosen": ("list", True),
        "written": ("str", False),
    },
}


class Empty(TypedDict):
    """A method that takes nothing. Still an object, so a parameter can be
    added later without a new shape.
    """



class PeerInfo(TypedDict):
    """Who is on the other end. Reported, never trusted for authorisation."""

    name: str
    version: str


class _HelloParamsRequired(TypedDict):
    protocol_version: int
    client: PeerInfo


class HelloParams(_HelloParamsRequired, total=False):
    capabilities: list[str]


class HelloResult(TypedDict):
    protocol_version: int
    core: PeerInfo
    capabilities: list[str]


class _SessionRequired(TypedDict):
    id: str
    mode: str
    workspace: str
    busy: bool


class Session(_SessionRequired, total=False):
    """A session as the core knows it. This is the authoritative shape a
    client resynchronises against.
    """

    title: str


class SessionRef(TypedDict):
    session_id: str


class _SessionCreateParamsRequired(TypedDict):
    pass


class SessionCreateParams(_SessionCreateParamsRequired, total=False):
    workspace: str
    mode: str


class SessionResult(TypedDict):
    session: Session


class SessionListResult(TypedDict):
    sessions: list[Session]


class SessionSendParams(TypedDict):
    session_id: str
    text: str


class AcceptedResult(TypedDict):
    """The turn was accepted. `message_id` correlates every message.* event
    that follows.
    """

    accepted: bool
    message_id: str


class CancelResult(TypedDict):
    cancelled: bool


class SetModeParams(TypedDict):
    session_id: str
    mode: str


class ModelResult(TypedDict):
    """Never carries a key. `configured` is how a client shows that a
    provider needs setting up without being told the secret.
    """

    provider: str
    model: str
    configured: bool


class _SetModelParamsRequired(TypedDict):
    model: str


class SetModelParams(_SetModelParamsRequired, total=False):
    provider: str


class _WorkspaceResultRequired(TypedDict):
    path: str


class WorkspaceResult(_WorkspaceResultRequired, total=False):
    name: str


class _QuestionOptionRequired(TypedDict):
    id: str
    label: str


class QuestionOption(_QuestionOptionRequired, total=False):
    """One row a person can pick. `id` is what travels back in `chosen`.
    `free` marks the write-your-own row, which carries typed text instead
    of a fixed label and is rendered differently.
    """

    description: str
    free: bool


class QuestionRequest(TypedDict):
    """A form the agent is waiting on, as a protocol primitive rather than a
    numbered list in prose. It carries *several* questions because the
    agent asks several at once — one round trip rather than four — so a
    client renders a form, not a prompt.
    """

    id: str
    session_id: str
    title: str
    questions: list[QuestionField]


class _QuestionResolvedRequired(TypedDict):
    id: str
    session_id: str


class QuestionResolved(_QuestionResolvedRequired, total=False):
    answers: list[QuestionAnswer]
    cancelled: bool


class _AnswerParamsRequired(TypedDict):
    id: str


class AnswerParams(_AnswerParamsRequired, total=False):
    answers: list[QuestionAnswer]
    cancelled: bool


class _PermissionRequestRequired(TypedDict):
    id: str
    session_id: str
    title: str
    options: list[str]


class PermissionRequest(_PermissionRequestRequired, total=False):
    """A tool call waiting on a person. `detail` is what the core already
    renders for a human; it is not a command to run.
    """

    detail: str


class PermissionResolved(TypedDict):
    id: str
    session_id: str
    choice: str


class PermissionReplyParams(TypedDict):
    id: str
    choice: str


class AckResult(TypedDict):
    ok: bool


class SessionEvent(TypedDict):
    session: Session


class MessageStarted(TypedDict):
    session_id: str
    message_id: str
    role: str


class _MessageDeltaRequired(TypedDict):
    session_id: str
    message_id: str
    text: str


class MessageDelta(_MessageDeltaRequired, total=False):
    """One piece of a streamed answer. `channel` separates the answer from
    extended thinking, so a client can show or hide reasoning without
    guessing from the text.
    """

    channel: str


class _MessageCompletedRequired(TypedDict):
    session_id: str
    message_id: str


class MessageCompleted(_MessageCompletedRequired, total=False):
    text: str
    cancelled: bool


class _ToolStartedRequired(TypedDict):
    session_id: str
    call_id: str
    name: str


class ToolStarted(_ToolStartedRequired, total=False):
    summary: str


class _ToolOutputRequired(TypedDict):
    session_id: str
    text: str


class ToolOutput(_ToolOutputRequired, total=False):
    """Incremental output from a running tool, such as a shell command's
    lines as they arrive. `call_id` is optional because the core does not
    tag streamed output with the call it came from, and two tools can run
    at once — attributing it to the most recently started call would be
    right most of the time and quietly wrong under parallel execution. A
    client shows it against the session unless a call is named.
    """

    call_id: str


class _ToolCompletedRequired(TypedDict):
    session_id: str
    call_id: str


class ToolCompleted(_ToolCompletedRequired, total=False):
    name: str
    summary: str
    elapsed_ms: int


class _ToolFailedRequired(TypedDict):
    session_id: str
    call_id: str
    error: str


class ToolFailed(_ToolFailedRequired, total=False):
    name: str


class ModeChanged(TypedDict):
    session_id: str
    mode: str


class _NotificationRequired(TypedDict):
    level: str
    text: str


class Notification(_NotificationRequired, total=False):
    """Something worth saying that is not part of an answer. `level` is
    advisory; a client may style it.
    """

    session_id: str


class _ErrorRequired(TypedDict):
    code: str
    message: str


class Error(_ErrorRequired, total=False):
    data: dict[str, Any]


class QuestionField(TypedDict):
    """One question within a form. `header` is its stable name and is what an
    answer is matched on — not the position, which would silently reattach
    every answer if a question were reordered.
    """

    header: str
    prompt: str
    options: list[QuestionOption]
    multiple: bool


class _QuestionAnswerRequired(TypedDict):
    header: str
    chosen: list[str]


class QuestionAnswer(_QuestionAnswerRequired, total=False):
    """What came back for one question. `chosen` holds option ids; `written`
    holds what was typed into the free row.
    """

    written: str
